import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import App from "./app";
import { getSession } from "@/auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const isDarkMode = true;
  return (
    <html lang="en" className={isDarkMode ? 'dark' : ''}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100 dark:bg-gradient-to-b dark:bg-black
        ]`}
      >
        <App session={session}>
          {children}
        </App>
      </body>
    </html>
  );
}
